version: 2

models:
  - name: raw_client
    description: "raw client data"
    columns:
      - name: CLIENT_ID
        description: "Primary Key for Client identification"
      - name: NAME
        description: "Client's first name"
      - name: GENDER
        description: "Client's gender"
      - name: Email
        description: "Client's email"