version: 2

models:
  - name: client
    identifier: bronze_client
    description: "client data email anonymized"
    columns:
      - name: CLIENT_ID
        description: "Primary Key for Client identification"
      - name: NAME
        description: "Client's first name"
      - name: GENDER
        description: "Client's gender"
      - name: Email
        description: "Client's email - anonymized"