version: 2

models:
  - name: brz_client
    alias: client
    description: "client data"
    columns:
      - name: CLIENT_ID
        description: "Primary Key for Client identification"
      - name: NAME
        description: "Client's first name"
      - name: GENDER
        description: "Client's gender"
      - name: Email
        description: "Client's email - anonymized"